/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_micropsi_eclipse_emotion3d_win32_FaceSurface */

#ifndef _Included_org_micropsi_eclipse_emotion3d_win32_FaceSurface
#define _Included_org_micropsi_eclipse_emotion3d_win32_FaceSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_micropsi_eclipse_emotion3d_win32_FaceSurface
 * Method:    initialize
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_emotion3d_win32_FaceSurface_initialize
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     org_micropsi_eclipse_emotion3d_win32_FaceSurface
 * Method:    resize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_emotion3d_win32_FaceSurface_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_micropsi_eclipse_emotion3d_win32_FaceSurface
 * Method:    updatebones
 * Signature: ([C[C)I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_emotion3d_win32_FaceSurface_updatebones
  (JNIEnv *, jobject, jcharArray, jcharArray);

/*
 * Class:     org_micropsi_eclipse_emotion3d_win32_FaceSurface
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_emotion3d_win32_FaceSurface_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
