#pragma once

#ifndef E42_SHADERCONSTANTS_H_INCLUDED
#define E42_SHADERCONSTANTS_H_INCLUDED

#define SHADERCONSTANT_NAME_NUMBONES					("c_iNumBones")

#define SHADERCONSTANT_SEMANTIC_WORLD					("WORLD")
#define SHADERCONSTANT_SEMANTIC_WORLDINVERSE			("WORLDINVERSE")
#define SHADERCONSTANT_SEMANTIC_VIEW					("VIEW")
#define SHADERCONSTANT_SEMANTIC_PROJECTION				("PROJECTION")
#define SHADERCONSTANT_SEMANTIC_WORLDVIEW				("WORLDVIEW")
#define SHADERCONSTANT_SEMANTIC_VIEWPROJECTION			("VIEWPROJECTION")
#define SHADERCONSTANT_SEMANTIC_WORLDVIEWPROJECTION		("WORLDVIEWPROJECTION")
#define SHADERCONSTANT_SEMANTIC_VIEWINVERSE				("VIEWINVERSE")

#define SHADERCONSTANT_SEMANTIC_NORMAL					("NORMAL")
#define SHADERCONSTANT_SEMANTIC_TANGENT					("TANGENT")
#define SHADERCONSTANT_SEMANTIC_BINORMAL				("BINORMAL")
#define SHADERCONSTANT_SEMANTIC_POSITION				("POSITION")
#define SHADERCONSTANT_SEMANTIC_COLOR					("COLOR")
#define SHADERCONSTANT_SEMANTIC_TEXCOORD				("TEXCOORD")
#define SHADERCONSTANT_SEMANTIC_BLENDINDICES			("BLENDINDICES")
#define SHADERCONSTANT_SEMANTIC_BLENDWEIGHTS			("BLENDWEIGHTS")

#define SHADERCONSTANT_NAME_WORLDMATRIXARRAY			("c_amWorldMatrixArray")

#define SHADERCONSTANT_NAME_MATERIALAMBIENT				("c_vMaterialAmbient")
#define SHADERCONSTANT_NAME_MATERIALDIFFUSE				("c_vMaterialDiffuse")
#define SHADERCONSTANT_NAME_MATERIALSPECULAR			("c_vMaterialSpecular")
#define SHADERCONSTANT_NAME_MATERIALEMISSIVE			("c_vMaterialEmissive")
#define SHADERCONSTANT_NAME_SPECULARPOWER				("c_fSpecularPower")

#define SHADERCONSTANT_NAME_DIFFUSEMAP					("c_tDiffuseMap")
#define SHADERCONSTANT_NAME_SPECULARMAP					("c_tSpecularMap")
#define SHADERCONSTANT_NAME_BUMPMAP						("c_tBumpMap")
#define SHADERCONSTANT_NAME_NORMALMAP					("c_tNormalMap")
#define SHADERCONSTANT_NAME_DETAILMAP					("c_tDetailMap")
#define SHADERCONSTANT_NAME_ENVIRONMENTMAP				("c_tEnvironmentMap")
#define SHADERCONSTANT_NAME_LIGHTMAP					("c_tLightMap")
#define SHADERCONSTANT_NAME_SHADOWMAP					("c_tShadowMap")

#define SHADERCONSTANT_NAME_LIGHTDIRECTION				("c_vLightDir")
#define SHADERCONSTANT_NAME_EYEPOSITION					("c_vEyePosition")

#define SHADERCONSTANT_NAME_TIME						("c_fTime")


#define SHADERCONSTANT_ANNOTATIONKEY_CONTEXT			("Context")
#define SHADERCONSTANT_ANNOTATIONVALUE_CONTEXT_OBJECT	("Object")
#define SHADERCONSTANT_ANNOTATIONVALUE_CONTEXT_SCENE	("Scene")


#endif // E42_SHADERCONSTANTS_H_INCLUDED
