/*
 * Created on 13.04.2005
 *
 */

package org.micropsi.comp.world;

import java.util.HashMap;
import java.util.Map;

/**This class is used to generate 'unique' worldobject names.
 * 
 * @author Matthias
 */
public class ObjectNameGenerator {
	
	private Map<String,Integer> nameIndexes = new HashMap<String,Integer>(40);

	public ObjectNameGenerator() {
	}
	
	/**
	 * This generates a name that is different from all other names generated by this object.
	 * The name is *not* garanteed to be unique in the world.
	 * 
	 * @param objectClass - the objectclass of the object to be named
	 * @return the name
	 */
	public String createName(String objectClass) {
		Integer index = nameIndexes.get(objectClass);
		int i;
		if (index == null) {
			i = 1;
		} else {
			i = index.intValue();
		}
		nameIndexes.put(objectClass, new Integer(i + 1));
		return objectClass + "-" + i;
	}
	
	/**
	 * Forget all names already used.
	 */
	public void reset() {
		nameIndexes.clear();
	}

}
