/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_micropsi_eclipse_viewer3d_win32_NebulaSurface */

#ifndef _Included_org_micropsi_eclipse_viewer3d_win32_NebulaSurface
#define _Included_org_micropsi_eclipse_viewer3d_win32_NebulaSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_micropsi_eclipse_viewer3d_win32_NebulaSurface
 * Method:    initialize
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_viewer3d_win32_NebulaSurface_initialize
  (JNIEnv *, jobject, jint, jcharArray);

/*
 * Class:     org_micropsi_eclipse_viewer3d_win32_NebulaSurface
 * Method:    resize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_viewer3d_win32_NebulaSurface_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_micropsi_eclipse_viewer3d_win32_NebulaSurface
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_micropsi_eclipse_viewer3d_win32_NebulaSurface_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
