/**
 * $Header: G:\DEV\Workspace\migration3.0\micropsi-cvs-repository\micropsi/org.micropsi.core/sources/org/micropsi/common/consoleservice/ConsoleQuestionTypeIF.java,v 1.2 2004/08/10 14:38:17 fuessel Exp $
 */
package org.micropsi.common.consoleservice;

public interface ConsoleQuestionTypeIF {
	
	/**
	 * Returns the question name. It is important that this name be unique, as the consoleservice will
	 * chose the questionType by the return value of this method when it is about to answer a question.
	 * The returned value must not change during runtime.
	 * @return the name of the question
	 */
	public String getQuestionName();

	/**
	 * Answers a question. The answer object should be auto-generated by the factory passed to this method,
	 * using the given question and step.
	 * @param factory The AnswerFactoryIF to be used for the creation of the answer
	 * @param question The question to be answered.
	 * @param step The current simulation step.
	 * @return an AnswerIF that contains the appropriate data. (@link AnswerIF)
	 */
	public AnswerIF answerQuestion(AnswerFactoryIF factory, QuestionIF question, long step);

}
